name: Streetfox
favicon: null
layout_spectrum: 0.9086022
typography_spectrum: 0.341869
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6D9092'
    - '#D3ECAB'
    - '#FD3F59'
    - '#FAC946'
    - '#9CB876'
  brandStrength: 0.25
  lightness: 0.6738351
  saturation: 0.6875
  rhythmicContrast: 0.3853047
purpose: []
