layout_spectrum: 0.9086022
typography_spectrum: 0.341869
color:
  saturation: 0.9874552
  lightness: 0.6738351
  brandStrength: 1
  brandColors:
    - '#6D9092'
    - '#D3ECAB'
    - '#FD3F59'
    - '#FAC946'
    - '#9CB876'
  rhythmicContrast: 0.3853047
name: Streetfox
