layout_spectrum: 0.9086022
color:
  saturation: 0.2113061
  lightness: 0.6525839
  brandStrength: 1
  brandColors:
    - '#6D9092'
    - '#D3ECAB'
    - '#FD3F59'
    - '#FAC946'
    - '#9CB876'
  rhythmicContrast: 0.2030673
typography_spectrum: 0.341869
name: Streetfox
